name: Github Actions Example

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: npm test
